### ISSUE TITLE
Explain how it works

### ISSUE THREAD

**Issue by vigna** [taiki-e/negative-impl#6]
I think it would be fantastic if you could comment a sample of the generated code in the README and explain why it works. I'm learning a lot from your code but some written explanation would be priceless. :)

**Comment by taiki-e** [comment]
As mentioned in the readme, it generates a trait implementation with a condition that will never be true.

For example, in the case of Unpin, the generated code is roughly as follows.

```rs
impl Unpin for $ty 
where
    PhantomPinned: Unpin, // PhantomPinned will never be Unpin.
{}
```

The actual generated code is a bit more complex because of hygiene and [to work around the limitations of Rust's type system](https://github.com/taiki-e/pin-project/issues/102#issuecomment-540472282).
